global:
  scrape_interval: 15s
  evaluation_interval: 30s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['localhost:8080', 'nestjs-starter.up.railway.app', 'nestjs-starter-test.up.railway.app']
